# Generated by Django 5.2.8 on 2026-01-15 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default='ORD-2213-14', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
