# Generated by Django 5.2.8 on 2026-01-31 17:22

import django.db.models.deletion
import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products_app', '0008_merge_0004_productview_0007_productreviews_user'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(default=orders.models.generate_order_id, editable=False, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Products_app.product'),
        ),
    ]
