# Generated by Django 5.2.8 on 2026-01-22 15:57

import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_product_alter_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(default=orders.models.generate_order_id, editable=False, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
