# Generated by Django 5.2.8 on 2026-01-28 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products_app', '0008_merge_0004_productview_0007_productreviews_user'),
        ('orders', '0003_alter_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Products_app.product'),
        ),
    ]
