# Generated by Django 5.2.8 on 2025-11-27 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paymentapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopUpMOdel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('COMPLETED', 'completed')], default='PENDING', max_length=10)),
                ('transaction_type', models.CharField(default='TOPUP', max_length=10)),
                ('reference', models.CharField(blank=True, max_length=36, unique=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paymentapp.buyerwallet')),
            ],
        ),
    ]
