# Generated by Django 5.2.8 on 2025-12-16 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentapp', '0003_merge_20251215_1410'),
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topupmodel',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_topup_wallet', to='paymentapp.vendorwallet'),
        ),
        migrations.AlterField(
            model_name='topupmodel',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topup_wallet', to='paymentapp.buyerwallet'),
        ),
    ]
