# Generated by Django 5.2.8 on 2026-01-30 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_topupmodel_vendor_alter_topupmodel_buyer'),
        ('orders', '0001_initial'),
    ]


    operations = [
        migrations.CreateModel(
            name='EscrowWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('held_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('HELD', 'held'), ('RELEASED', 'released'), ('REFUNDED', 'refunded')], default='HELD', max_length=10)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escrow', to='orders.order')),
            ],
        ),
    ]
