# Generated by Django 5.2.8 on 2026-04-07 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_escrowwallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topupmodel',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
