# Generated by Django 5.2.8 on 2025-12-13 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerwallet',
            name='balance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vendorwallet',
            name='balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
