# Generated by Django 5.2.8 on 2025-12-15 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paymentapp', '0002_alter_buyerwallet_balance_alter_vendorwallet_balance'),
        ('paymentapp', '0002_transaction_product'),
    ]

    operations = [
    ]
