# Generated by Django 5.2.8 on 2025-12-16 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paymentapp', '0003_merge_20251215_0856'),
        ('paymentapp', '0003_merge_20251215_1410'),
    ]

    operations = [
    ]
