# Generated by Django 5.2.8 on 2026-01-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
