# Generated by Django 5.2.8 on 2026-01-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_alter_messagemodel_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
