# Generated by Django 5.2.8 on 2026-01-03 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_alter_messagemodel_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagemodel',
            options={'ordering': ['timestamp']},
        ),
        migrations.RemoveField(
            model_name='conversationmodel',
            name='last_seen',
        ),
        migrations.RemoveField(
            model_name='conversationmodel',
            name='online',
        ),
    ]
