# Generated by Django 5.2.8 on 2025-12-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='institute',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
