# Generated by Django 5.2.8 on 2025-12-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_customusermodel_phone_alter_customusermodel_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
