# Generated by Django 5.2.8 on 2025-12-14 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_customusermodel_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='profile_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
