# Generated by Django 5.2.8 on 2025-12-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_customusermodel_profile_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
