# Generated by Django 5.2.8 on 2025-12-14 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_customusermodel_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusermodel',
            name='profile_url',
        ),
    ]
