# Generated by Django 5.2.8 on 2025-12-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_customusermodel_profile_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='profile_url',
            field=models.TextField(default='https://icuklzexzhusblkzglnr.supabase.co/storage/v1/object/public/marketplace/profiie_pictures/freepik__adjust__23179.png', null=True),
        ),
    ]
