# Generated by Django 5.2.8 on 2026-01-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_customusermodel_profile_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
