# Generated by Django 5.2.8 on 2025-12-30 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercategorymodel',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
