# Generated by Django 5.2.8 on 2025-12-04 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_remove_vendorcontents_likes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentreview',
            name='rating',
        ),
    ]
