# Generated by Django 5.2.8 on 2025-12-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_remove_contentreview_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorcontents',
            name='pictures',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='vendorcontents',
            name='video',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
