# Generated by Django 5.2.8 on 2026-01-03 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_alter_vendorcontents_pictures_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contentreview',
            unique_together=set(),
        ),
    ]
