# Generated by Django 5.2.8 on 2025-12-13 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products_app', '0004_alter_product_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='vendor_name',
            new_name='vendor_id',
        ),
    ]
