<<<<<<< HEAD
# Generated by Django 5.2.8 on 2025-12-15 08:56
=======
# Generated by Django 5.2.8 on 2025-12-15 14:14
>>>>>>> b9dedb4 (fixed the top error)

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products_app', '0004_productview'),
        ('Products_app', '0007_productreviews_user'),
    ]

    operations = [
    ]
