# Generated by Django 5.2.8 on 2026-04-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitlistmodel',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
